# HW_NLP_01_MohsenMohebbi

---
This exercise consists of four main sections and includes four primary tasks:

1. **Data Extraction (Web Scraping):**  
   Use Selenium and BeautifulSoup to extract data from the Jobinja website:  
   https://jobinja.ir/

2. **Data Cleaning:**  
   Clean a new dataset using regular expressions (`regex`) and (`hazm`):  
   https://www.kaggle.com/datasets/amirpourmand/asriran-news

3. **Content-Based Search Engine:**  
   Build a search engine using **TF-IDF** and **Cosine Similarity**.

4. **Multiclass News Topic Classification:**  
   Classify news articles into multiple topic categories.

## Task 1: **Data Extraction with Selenium and BeautifulSoup**  
   **Goal:** Learn how to scrape data from websites with multiple pages (pagination) and extract structured data.

### Workflow Steps

1. **Setup:**
   - Use Selenium to open the search results page for "Data Scientist" or "Python Developer".    


2. **Page Navigation:**
   - Write a loop to extract data from the current page, then use Selenium to click the "Next" button. Perform this for at least 3 result pages.

3. **Extraction:**
   - Use BeautifulSoup to parse the HTML of each page and extract the following information for each job listing:
     - Job Title
     - Company Name
     - Location (City)

4. **Output:**
   - Store the extracted data in a Pandas DataFrame and export it as a CSV file.

In [1]:
!pip install selenium

Collecting selenium
  Downloading selenium-4.48.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: certifi>=2026.2.25 in C:\Mohsen Folder\Ai Bootcamp\Ai Bootcamp\.venv_py3_12_10\Lib\site-packages (from selenium) (2026.7.22)
Collecting trio<1.0,>=0.31.0 (from selenium)
  Downloading trio-0.34.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in C:\Mohsen Folder\Ai Bootcamp\Ai Bootcamp\.venv_py3_12_10\Lib\site-packages (from selenium) (4.16.0)
Collecting urllib3<3.0,>=2.6.3 (from urllib3[socks]<3.0,>=2.6.3->selenium)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting websocket-client<2.0,>=1.8.0 (from selenium)
  Downloading websocket_client-1.9.1-py3-none-any.whl.metadata (8.3 kB)
Collecting attrs>=23.2.0 (from trio<1.0,>=0.31.0->selenium)
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting sortedcontainers (from trio<1.0,>=0.31.0->selenium)
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: idna in C:\Mohsen Folder\Ai Bootcamp\Ai Bootcamp\.venv_py3_12_10\Lib\site-packages (from trio<1.0,>=0.31.0->selenium) (3.19)
Collecting outcome (from trio<1.0,>=0.31.0->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Collecting sniffio>=1.3.0 (from trio<1.0,>=0.31.0->selenium)
  Downloading sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting cffi>=1.14 (from trio<1.0,>=0.31.0->selenium)
  Downloading cffi-2.1.1-cp312-cp312-win_amd64.whl.metadata (2.6 kB)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium)
  Downloading wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Collecting pysocks!=1.5.7,<2.0,>=1.5.6 (from urllib3[socks]<3.0,>=2.6.3->selenium)
  Downloading PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
Collecting pycparser (from cffi>=1.14->trio<1.0,>=0.31.0->selenium)
  Downloading pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: h11<1,>=0.16.0 in C:\Mohsen Folder\Ai Bootcamp\Ai Bootcamp\.venv_py3_12_10\Lib\site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Downloading selenium-4.48.0-py3-none-any.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.6 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.6 MB 2.2 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.6 MB 2.9 MB/s eta 0:00:03
   ---------- ----------------------------- 2.6/9.6 MB 3.5 MB/s eta 0:00:02
   -------------- ------------------------- 3.4/9.6 MB 4.0 MB/s eta 0:00:02
   ------------------- -------------------- 4.7/9.6 MB 4.2 MB/s eta 0:00:02
   ------------------------ --------------- 5.8/9.6 MB 4.4 MB/s eta 0:00:01
   -------------------------- ------------- 6.3/9.6 MB 4.4 MB/s eta 0:00:01
   ----------------------------------- ---- 8.4/9.6 MB 4.7 MB/s eta 0:00:01
   ------------------------------------ --- 8.7/9.6 MB 4.3 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.6 MB 4.3 MB/s eta 0:00:01
   ---------------------------------------- 9.6/9.6 MB 4.1 MB/s  0:00:02
Downloading trio-0.34.0-py3-none-any.whl (511 kB)
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
Downloading websocket_client-1.9.1-py3-none-any.whl (95 kB)
Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
Downloading cffi-2.1.1-cp312-cp312-win_amd64.whl (185 kB)
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Downloading wsproto-1.3.2-py3-none-any.whl (24 kB)
Downloading pycparser-3.0-py3-none-any.whl (48 kB)
Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Installing collected packages: sortedcontainers, wsproto, websocket-client, urllib3, sniffio, pysocks, pycparser, attrs, outcome, cffi, trio, trio-websocket, selenium

   --- ------------------------------------  1/13 [wsproto]
   ------ ---------------------------------  2/13 [websocket-client]
   ------ ---------------------------------  2/13 [websocket-client]
   ------ ---------------------------------  2/13 [websocket-client]
   ------ ---------------------------------  2/13 [websocket-client]
   ------ ---------------------------------  2/13 [websocket-client]
   --------- ------------------------------  3/13 [urllib3]
   --------- ------------------------------  3/13 [urllib3]
   --------- ------------------------------  3/13 [urllib3]
   ------------ ---------------------------  4/13 [sniffio]
   ------------------ ---------------------  6/13 [pycparser]
   --------------------- ------------------  7/13 [attrs]
   --------------------------- ------------  9/13 [cffi]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------ --------- 10/13 [trio]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ------------------------------------ --- 12/13 [selenium]
   ---------------------------------------- 13/13 [selenium]

Successfully installed attrs-26.1.0 cffi-2.1.1 outcome-1.3.0.post0 pycparser-3.0 pysocks-1.7.1 selenium-4.48.0 sniffio-1.3.1 sortedcontainers-2.4.0 trio-0.34.0 trio-websocket-0.12.2 urllib3-2.7.0 websocket-client-1.9.1 wsproto-1.3.2

In [2]:
!pip install beautifulsoup4

Collecting beautifulsoup4
  Downloading beautifulsoup4-4.15.0-py3-none-any.whl.metadata (3.8 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4)
  Downloading soupsieve-2.9.2-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in C:\Mohsen Folder\Ai Bootcamp\Ai Bootcamp\.venv_py3_12_10\Lib\site-packages (from beautifulsoup4) (4.16.0)
Downloading beautifulsoup4-4.15.0-py3-none-any.whl (109 kB)
Downloading soupsieve-2.9.2-py3-none-any.whl (37 kB)
Installing collected packages: soupsieve, beautifulsoup4

   -------------------- ------------------- 1/2 [beautifulsoup4]
   -------------------- ------------------- 1/2 [beautifulsoup4]
   -------------------- ------------------- 1/2 [beautifulsoup4]
   ---------------------------------------- 2/2 [beautifulsoup4]

Successfully installed beautifulsoup4-4.15.0 soupsieve-2.9.2

In [3]:
!pip install chromedriver-py

Collecting chromedriver-py
  Downloading chromedriver_py-151.0.7922.76-py3-none-any.whl.metadata (2.0 kB)
Downloading chromedriver_py-151.0.7922.76-py3-none-any.whl (56.0 MB)
   ---------------------------------------- 0.0/56.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/56.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/56.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/56.0 MB ? eta -:--:--
    --------------------------------------- 0.8/56.0 MB 2.1 MB/s eta 0:00:27
   - -------------------------------------- 1.8/56.0 MB 3.1 MB/s eta 0:00:18
   - -------------------------------------- 2.4/56.0 MB 3.2 MB/s eta 0:00:17
   -- ------------------------------------- 3.1/56.0 MB 3.0 MB/s eta 0:00:18
   -- ------------------------------------- 3.4/56.0 MB 2.8 MB/s eta 0:00:19
   --- ------------------------------------ 4.5/56.0 MB 3.0 MB/s eta 0:00:18
   --- ------------------------------------ 4.7/56.0 MB 2.9 MB/s eta 0:00:18
   --- ------------------------------------ 5.5/56.0 MB 3.0 MB/s eta 0:00:17
   ---- ----------------------------------- 6.8/56.0 MB 3.3 MB/s eta 0:00:16
   ----- ---------------------------------- 7.6/56.0 MB 3.3 MB/s eta 0:00:15
   ------ --------------------------------- 8.7/56.0 MB 3.5 MB/s eta 0:00:14
   ------ --------------------------------- 9.7/56.0 MB 3.6 MB/s eta 0:00:13
   ------- -------------------------------- 10.7/56.0 MB 3.7 MB/s eta 0:00:13
   -------- ------------------------------- 11.8/56.0 MB 3.8 MB/s eta 0:00:12
   --------- ------------------------------ 13.1/56.0 MB 3.9 MB/s eta 0:00:11
   --------- ------------------------------ 13.6/56.0 MB 3.9 MB/s eta 0:00:12
   ---------- ----------------------------- 14.4/56.0 MB 3.9 MB/s eta 0:00:11
   ----------- ---------------------------- 15.5/56.0 MB 3.9 MB/s eta 0:00:11
   ----------- ---------------------------- 16.3/56.0 MB 4.0 MB/s eta 0:00:11
   ------------ --------------------------- 17.0/56.0 MB 3.9 MB/s eta 0:00:10
   ------------ --------------------------- 17.8/56.0 MB 3.9 MB/s eta 0:00:10
   ------------- -------------------------- 18.9/56.0 MB 3.9 MB/s eta 0:00:10
   ------------- -------------------------- 19.4/56.0 MB 3.9 MB/s eta 0:00:10
   -------------- ------------------------- 20.4/56.0 MB 3.9 MB/s eta 0:00:10
   --------------- ------------------------ 21.2/56.0 MB 3.9 MB/s eta 0:00:09
   ---------------- ----------------------- 22.5/56.0 MB 4.0 MB/s eta 0:00:09
   ---------------- ----------------------- 23.6/56.0 MB 4.0 MB/s eta 0:00:09
   ----------------- ---------------------- 24.6/56.0 MB 4.1 MB/s eta 0:00:08
   ------------------ --------------------- 25.4/56.0 MB 4.1 MB/s eta 0:00:08
   ------------------ --------------------- 26.5/56.0 MB 4.1 MB/s eta 0:00:08
   ------------------- -------------------- 27.5/56.0 MB 4.2 MB/s eta 0:00:07
   -------------------- ------------------- 28.8/56.0 MB 4.2 MB/s eta 0:00:07
   --------------------- ------------------ 30.1/56.0 MB 4.3 MB/s eta 0:00:07
   ---------------------- ----------------- 31.5/56.0 MB 4.3 MB/s eta 0:00:06
   ----------------------- ---------------- 32.5/56.0 MB 4.3 MB/s eta 0:00:06
   ------------------------ --------------- 33.8/56.0 MB 4.4 MB/s eta 0:00:06
   ------------------------ --------------- 34.9/56.0 MB 4.4 MB/s eta 0:00:05
   ------------------------- -------------- 35.7/56.0 MB 4.4 MB/s eta 0:00:05
   -------------------------- ------------- 37.0/56.0 MB 4.4 MB/s eta 0:00:05
   --------------------------- ------------ 38.0/56.0 MB 4.4 MB/s eta 0:00:05
   --------------------------- ------------ 39.1/56.0 MB 4.5 MB/s eta 0:00:04
   ---------------------------- ----------- 39.6/56.0 MB 4.4 MB/s eta 0:00:04
   ----------------------------- ---------- 40.6/56.0 MB 4.4 MB/s eta 0:00:04
   ----------------------------- ---------- 41.9/56.0 MB 4.4 MB/s eta 0:00:04
   ------------------------------ --------- 42.7/56.0 MB 4.5 MB/s eta 0:00:03
   ------------------------------- -------- 43.8/56.0 MB 4.5 MB/s eta 0:00:03
   ------------------------------- -------- 44.8/56.0 MB 4.5 MB/s eta 0:00:03
   -------------------------------- ------- 45.9/56.0 MB 4.5 MB/s eta 0:00:03
   --------------------------------- ------ 47.2/56.0 MB 4.5 MB/s eta 0:00:02
   ---------------------------------- ----- 48.2/56.0 MB 4.5 MB/s eta 0:00:02
   ----------------------------------- ---- 49.3/56.0 MB 4.5 MB/s eta 0:00:02
   ----------------------------------- ---- 50.3/56.0 MB 4.5 MB/s eta 0:00:02
   ------------------------------------ --- 51.4/56.0 MB 4.5 MB/s eta 0:00:02
   ------------------------------------- -- 52.2/56.0 MB 4.5 MB/s eta 0:00:01
   -------------------------------------- - 53.5/56.0 MB 4.5 MB/s eta 0:00:01
   -------------------------------------- - 54.5/56.0 MB 4.6 MB/s eta 0:00:01
   ---------------------------------------  55.8/56.0 MB 4.6 MB/s eta 0:00:01
   ---------------------------------------- 56.0/56.0 MB 4.6 MB/s  0:00:12
Installing collected packages: chromedriver-py
Successfully installed chromedriver-py-151.0.7922.76

In [ ]:
# Packages

import json
import time
import numpy as np
import pandas as pd
from typing import Dict, List
#---------------------------------------
# Generating Random Time Intervals
import random
#---------------------------------------
# Creating Simple Classes for Storing Settings
from dataclasses import dataclass
#---------------------------------------
# Browser Creation and Control with Selenium
from selenium import webdriver
#---------------------------------------
# Chrome Settings:
# Run the browser in headless mode
# Disable notifications
# Set the browser language
from selenium.webdriver.chrome.options import Options
#---------------------------------------
# Specifying the ChromeDriver Path in Selenium
from selenium.webdriver.chrome.service import Service
#---------------------------------------
# Selecting a Method for Locating Web Elements
from selenium.webdriver.common.by import By
#---------------------------------------
# Simulate keyboard keys such as Enter, Tab, and Escape
from selenium.webdriver.common.keys import Keys
#---------------------------------------
# Element Readiness Conditions
from selenium.webdriver.support import expected_conditions as EC
#---------------------------------------
# Waiting for a Specific Condition on the Page
from selenium.webdriver.support.ui import WebDriverWait
#---------------------------------------
# Analyzing and Extracting Information from Retrieved HTML
from bs4 import BeautifulSoup
#---------------------------------------
# install googledrive
from chromedriver_py import binary_path

In [6]:
print("Path of choromdriver")
print(binary_path)

Path of choromdriver
c:\Mohsen Folder\Ai Bootcamp\Ai Bootcamp\.venv_py3_12_10\Lib\site-packages\chromedriver_py\chromedriver_win64.exe

In [3]:
def open_jobinja_search(keyword):
    options = Options()
    options.add_argument("--start-maximized")
    options.add_argument("--disable-notifications")
    options.add_argument("--lang=fa")

    service = Service(binary_path)
    driver = webdriver.Chrome(service=service, options=options)

    driver.get("https://jobinja.ir/")

    # Wait for Popup
    wait = WebDriverWait(driver, 30)
    # Close popup
    close_popup = wait.until(
        EC.element_to_be_clickable(
            (
                By.XPATH,
                "//a[contains(@href, 'user-redirect') "
                "and contains(@href, 'commands') "
                "and contains(normalize-space(.), 'نمی‌خواهم')]"
            )
        )
    )

    close_popup.click()

    wait.until(EC.invisibility_of_element(close_popup))

    # Find serche window
    search_box = wait.until(
        EC.element_to_be_clickable(
            (By.XPATH,
             "//input[contains(@placeholder, 'عنوان شغلی، نام شرکت، مهارت')]")
        )
    )

    search_box.clear()
    search_box.send_keys(keyword)
    search_box.send_keys(Keys.ENTER)

    return driver


SEARCH_KEYWORD = "برنامه نویس پایتون"
driver = open_jobinja_search(SEARCH_KEYWORD)



all_jobs_data = []
NUM_PAGES = 3
# Change number to Farsi
fa_digits = {'1': '۱', '2': '۲', '3': '۳', '4': '۴', '5': '۵'}

for current_page in range(1, NUM_PAGES + 1):
    print(f"--- Scraping Page {current_page} ---")

    # Chcke this page, load?
    WebDriverWait(driver, 15).until(
        EC.presence_of_element_located((By.CSS_SELECTOR, "li.c-jobListView__item"))
    )

    # HTML Parser
    soup = BeautifulSoup(driver.page_source, "html.parser")
    job_cards = soup.select("li.c-jobListView__item")

    for job in job_cards:
        # Job titel
        title_tag = job.select_one("h2.c-jobListView__title a.c-jobListView__titleLink")
        title = title_tag.get_text(strip=True) if title_tag else None

        # list of Company Name, city and ...
        meta_items = job.select("ul.c-jobListView__meta li.c-jobListView__metaItem")
        
        # Company Name
        company = meta_items[0].get_text(strip=True) if len(meta_items) > 0 else ""
        
        # City
        location = meta_items[1].get_text(strip=True) if len(meta_items) > 1 else ""

        if title:
            all_jobs_data.append({
                "job_title": title,
                "company_name": company,
                "location": location,
                "page": current_page
            })

    print(f"Extracted {len(job_cards)} jobs from page {current_page}.")

    # Go to next page and scrole
    if current_page < NUM_PAGES:
        next_page_num = str(current_page + 1)
        next_page_fa = fa_digits.get(next_page_num, next_page_num)

        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(1.5)

        next_page_button = WebDriverWait(driver, 10).until(
            EC.presence_of_element_located((
                By.XPATH,
                f"//a[contains(@href, 'page={next_page_num}') or normalize-space(text())='{next_page_num}' or normalize-space(text())='{next_page_fa}']"
            ))
        )
        driver.execute_script("arguments[0].click();", next_page_button)
        time.sleep(3)

# Save ad CSV by pandas
df_jobs = pd.DataFrame(all_jobs_data)
df_jobs.to_csv("jobinja_jobs.csv", index=False, encoding="utf-8-sig")

print(f"\nCompleted! Total jobs: {len(df_jobs)}")
display(df_jobs.head(10))

--- Scraping Page 1 ---
Extracted 20 jobs from page 1.
--- Scraping Page 2 ---
Extracted 20 jobs from page 2.
--- Scraping Page 3 ---
Extracted 20 jobs from page 3.

Completed! Total jobs: 60

,job_title,company_name,location,page
0,توسعه دهنده پایتون (Python Software Engineer-A...,رهند هوشمند نوین داده | Rahand Hoshmand Novin ...,تهران، تهران,1
1,برنامه‌نویس پایتون (Python/Django-اصفهان),دانش بنیان مهندسی ارتباطی پیام پرداز | Payam P...,اصفهان، اصفهان,1
2,برنامه‌نویس Python,همیان | Hamyan,تهران، تهران,1
3,برنامه‌نویس ارشد پایتون,نت‌بان شریف | NetBaan Sharif,تهران، تهران,1
4,طراح صنعتی(فلاسک-مشهد-دورکاری),استودیو کوروش | Cyrus Studio,خراسان رضوی، مشهد,1
5,توسعه‌دهنده بک‌اند (Python-Django-کرج),میزگرد | Mizegerd,البرز، کرج,1
6,Python Developer,گروه مالی هامرز | Hummers Group,تهران، تهران,1
7,برنامه‌نویس (Python / Django),فناوری اطلاعات رسپینا رادین | Respina Radyn IT Co,تهران، تهران,1
8,برنامه‌نویس ارشد پایتون (دورکاری),پایا | RCP,تهران، تهران,1
9,توسعه‌دهنده بک‌اند (Java-Backend Developer),دانش رفاه پردیس | Danesh Refah Pardis,تهران، تهران,1

## Task 2: Data Cleaning Using `hazm` and `regex`

**Goal:** Master text normalization, noise removal, and build a preprocessing pipeline on real-world datasets.

**Task Description:** Load a DataFrame containing Persian text (e.g., Digikala reviews, SnappFood reviews, or news). You can use the dataset from Task 4. Write a function named `clean_persian_text(text)` that performs the following steps in sequence, then apply it across the entire text column using the `.apply()` method.

### Dataset
- **URL:** [Asriran News Dataset on Kaggle](https://www.kaggle.com/datasets/amirpourmand/asriran-news)

### Steps to Perform the Work:

1. **Noise Removal with Regex:**

2. **Fixing Word Elongation:**
   - Use Regex to correct words whose letters have been excessively repeated.

3. **Normalization with Hazm:**
   - Pass the text to Hazm library's `Normalizer` to correct spacing, semi-spaces, and character unification (such as converting Arabic 'ی' to Persian 'ی').

4. **Stopwords Removal:**
   - Tokenize the text with Hazm. Remove standard Persian Stopwords, but be careful to exclude negation words (like "نه", "نیست", "نمی", "نبود") from the Stopwords list so they are not deleted! Otherwise, the meaning of the text will be completely lost.

5. **Final Analysis:**
   - After applying this pipeline to the entire dataframe, write code to print the top 10 most frequent words across the cleaned dataframe. (If words like "از", "به", or "که" are in this list, it means your pipeline did not work correctly).

In [1]:
import os ,math
import numpy as np
import pandas as pd
import re
from hazm import Normalizer, word_tokenize, stopwords_list

Read data

In [2]:
df_master = pd.read_csv("asriran.csv")

In [3]:
df_master.head()

,title,shortlink,time,service,subgroup,abstract,body
0,پلیس: جرائم خشن و مسلحانه در تهران کاهش یافته است,https://www.asriran.com/003YoB,۰۸:۴۱ - ۲۳ تير ۱۴۰۱,صفحه نخست,عمومی,آمارهای پلیس نشان می‌دهد که جرائم خشن و مسلحان...,رئیس پلیس آگاهی تهران بزرگ اعلام کرد که موضوع ...
1,"وزیر بهداشت:\r\nآغاز اجرای طرح جامع ""دارویار""/...",https://www.asriran.com/003YoC,۰۸:۴۷ - ۲۳ تير ۱۴۰۱,صفحه نخست,اخبار سلامت,هدف اصلی وزارت بهداشت از این طرح این است که پو...,"وزیر بهداشت جزییات طرح ""دارویار"" که اجرای آن آ..."
2,وزارت بهداشت: قیمت دارو برای مصرف کننده ثابت م...,https://www.asriran.com/003YoF,۰۹:۰۸ - ۲۳ تير ۱۴۰۱,صفحه نخست,اجتماعی,NaN,سخنگوی وزارت بهداشت، درمان و آموزش پزشکی در تو...
3,معاون رئیسی: مردم به زودی شاهد اثرات مثبت اقدا...,https://www.asriran.com/003YZP,۱۶:۴۶ - ۱۶ تير ۱۴۰۱,صفحه نخست,سیاسی,معاون امور مجلس رئیس جمهور: استان گیلان دارای ...,معاون رئیس جمهور گفت: دولت برنامه های راهبردی ...
4,دستگیری سارق ۲۰ هزار دلاری ارز دیجیتال در گلستان,https://www.asriran.com/003YZN,۱۶:۴۱ - ۱۶ تير ۱۴۰۱,صفحه نخست,اجتماعی,شهروندان توصیه‌های پلیس فتا را جدی بگیرند و در...,رییس پلیس فتا فرماندهی انتظامی گلستان گفت: سار...

In [4]:
df_master.info()

<class 'pandas.DataFrame'>
RangeIndex: 339834 entries, 0 to 339833
Data columns (total 7 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   title      339834 non-null  str
 1   shortlink  339834 non-null  str
 2   time       339834 non-null  str
 3   service    339834 non-null  str
 4   subgroup   339834 non-null  str
 5   abstract   155497 non-null  str
 6   body       295560 non-null  str
dtypes: str(7)
memory usage: 18.1 MB

In [5]:
print("Columns have Nan value: ")
df_master.isna().sum().loc[lambda x: x > 0]

Columns have Nan value:

abstract    184337
body         44274
dtype: int64

In [ ]:
# 1. Regex:Remove Noise

def remove_noise_regex(text: str) -> str:
    """
    Give one Text:   
    Remove HTML Tag  
    Remove Links  
    Remove Email  
    Remove Charechters u0600 and u06ff  
    Remove extera space  
    """
    text = re.sub(r'<.*?>', ' ', text) # Remove HTML Tag 
    text = re.sub(r'https?://\S+|www\.\S+', ' ', text) # Remove Links
    text = re.sub(r'\S+@\S+', ' ', text) # Remove Email
    text = re.sub(r'[^\w\s\u0600-\u06FF]', ' ', text) # Remove Charechters
    text = re.sub(r'\s+', ' ', text) # Remove extera space 
    return text.strip()



normalizer = Normalizer()

negation_words = {'نه', 'نیست', 'نیستند', 'نیستم', 'نیستیم', 'نیستید', 
                  'نمی', 'نمی‌شود', 'نمی‌کند', 'نمی‌تواند', 'نبود', 'نبوده', 
                  'نبودند', 'نبودم', 'نبودیم', 'نشد', 'نشده', 'نشده‌اند'}

stopwords = set(stopwords_list()) - negation_words

# 2. hazm
def clean_persian_text(text: str) -> str:
    """
    Give one text:   
    Remove Noise by `remove_noise_regex`   
    Remove duplicate Charachters   
    Normslizer by hazm   
    Tokenizer
    """
    if not isinstance(text, str) or pd.isna(text):
        return ""
    # Remove Noise
    text = remove_noise_regex(text)
    
    # Remove duplicate Charachters
    text = re.sub(r'(.)\1{2,}', r'\1', text)

    # Normslizer by hazm
    text = normalizer.normalize(text)
    
    # Tokenizer
    tokens = word_tokenize(text)
    meaningful_tokens = [w for w in tokens if w not in stopwords and len(w) > 1]
    
    return " ".join(meaningful_tokens)


df_master['body_clean'] = df_master['body'].apply(clean_persian_text)

In [9]:
import re
import pandas as pd
from hazm import Normalizer, word_tokenize, stopwords_list

# 2nd way
RE_HTML = re.compile(r'<[^>]*>')
RE_URL = re.compile(r'https?://\S+|www\.\S+')
RE_EMAIL = re.compile(r'\S+@\S+')
RE_NON_PERSIAN = re.compile(r'[^\w\s\u0600-\u06FF]')
RE_REPEAT = re.compile(r'(.)\1{2,}')
RE_SPACES = re.compile(r'\s+')

normalizer = Normalizer()

negation_words = {'نه', 'نیست', 'نیستند', 'نیستم', 'نیستیم', 'نیستید', 
                  'نمی', 'نمی‌شود', 'نمی‌کند', 'نمی‌تواند', 'نبود', 'نبوده', 
                  'نبودند', 'نبودم', 'نبودیم', 'نشد', 'نشده', 'نشده‌اند'}
stopwords = set(stopwords_list()) - negation_words

def clean_persian_text(text: str) -> str:
    if not isinstance(text, str) or not text:
        return ""
    
    text = RE_HTML.sub(' ', text)
    text = RE_URL.sub(' ', text)
    text = RE_EMAIL.sub(' ', text)
    text = RE_NON_PERSIAN.sub(' ', text)
    text = RE_REPEAT.sub(r'\1', text)
    text = RE_SPACES.sub(' ', text).strip()
    
    if not text:
        return ""

    # hazm
    text = normalizer.normalize(text)
    tokens = word_tokenize(text)
    meaningful_tokens = [w for w in tokens if w not in stopwords and len(w) > 1]
    
    return " ".join(meaningful_tokens)


df_master['body_clean'] = df_master['body'].apply(clean_persian_text)

KeyboardInterrupt:

In [ ]:
from collections import Counter
all_words = " ".join(df_master['body_clean']).split()
Counter(all_words).most_common(10)

[('ایران', 204),
 ('کشور', 135),
 ('سال', 132),
 ('مردم', 104),
 ('گزارش', 98),
 ('قرار', 91),
 ('پلیس', 89),
 ('دولت', 88),
 ('اعلام', 84),
 ('روز', 83)]

## Task3: Movie Recommendation Model (TF-IDF and Cosine Similarity)

**Goal:** Build a simple content-based recommendation model using Vector Space Models.

**Implementation Steps:**

1. **Dataset:** Download the `TMDB 5000 Movie Dataset` from Kaggle.
   - **Important Note:** This dataset has two files. You only need to load the `tmdb_5000_movies.csv` file. For this exercise, keep only the `title` (movie name) and `overview` (plot summary) columns. (Of course, rows where `overview` is `NaN` or empty should be dropped.)

2. **Vectorization:** Convert the plot summaries into a numerical matrix using `TfidfVectorizer` (scikit-learn library). Use the `overview` column to build a stopword-removed, English-language TF-IDF matrix (`stop_words='english'`).

3. **Recommendation Model:** Write a function named `get_movie_recommendation(movie_title)`.

4. **Cosine Similarity:** Within the function, measure the cosine similarity between the TF-IDF vector of the input movie and all other movie vectors in the dataset.

5. **Output:** Sort the similarities and return the 5 movies with the highest similarity.

6. **Test:** If the movie name is `"The Dark Knight"`, write the function output. Are any of the other recommended movies or their plots action-oriented?




### Dataset
- **URL:** [TMDB 5000 Movie Dataset on Kaggle](https://www.kaggle.com/datasets/tmdb/tmdb-movie-metadata?resource=download)